### ISSUE TITLE
Site crashes whenever I click anything

### ISSUE THREAD

**Issue by petroseskinder** [andyfangdz/resume#17]
I was trying to download the pdf copy of your cv/resume. However, the site immediately stops rendering anything. This issue occurs when I try to 1) toggle between cv and resume, 2) download the pdf, 3) display the seal. 

Below, is what happens when I click the download button:

![andy_website](https://user-images.githubusercontent.com/5799696/31674257-5a0c2e72-b32f-11e7-949f-48dfd39b9273.gif)

**Comment by andyfangdz** [comment]
lol just saw this, could be something to do with React 16 update

**Comment by andyfangdz** [comment]
Thanks for raising this issue @petroseskinder. I fixed this by updating a few packages.
